### ISSUE TITLE
可否生成一套能替换宋体（simsun.ttf simsunb.ttf ）的字体

### ISSUE THREAD

**Issue by zwh8800** [chenh96/yahei-sarasa#1]
感谢大佬提供的字体 使用了之后效果很好
但是发现还是有部分顽固软件坚持使用宋体
希望能生成一套sarasa -> simsun的字体用来替换系统宋体

**Comment by chenh96** [comment]
目前 Windows 11 下系统 UI 基本已经没有宋体了，最好是能提供一下样例让我可以测试。
至于浏览器，我写了一套暂行的脚本来替换所有的字体到微软雅黑（部分不规范的网站，图标无法显示），你可以试试 :
[https://greasyfork.org/zh-CN/scripts/474592-%E9%92%A6%E5%AE%9A%E5%AD%97%E4%BD%93](url)

**Comment by zwh8800** [comment]
我这目前体感比较明显的是steam刚启动时自动更新的界面，还有就是部分软件的安装包
浏览器我试下 感谢

**Comment by zwh8800** [comment]
![image](https://github.com/chenh96/yahei-sarasa/assets/6185988/7eb833f9-eac7-4338-956a-ebfad4a05fd5)
刚刚又找到一个样例，nVidia的GeForce experience也用了宋体 太丑了

**Comment by chenh96** [comment]
我在 Release 中上传了替换好的宋体，麻烦你试用一下吧。

**Comment by zwh8800** [comment]
感谢大佬

**Comment by zwh8800** [comment]
![image](https://github.com/chenh96/yahei-sarasa/assets/6185988/df7579fd-a808-49e3-835c-a5674b4ee173)
用上了 效果很赞！
