### ISSUE TITLE
脚本报错无法运行

### ISSUE THREAD

**Issue by ffainy** [chenh96/yahei-sarasa#2]
你好，因为想用`Sarasa UI CL`做替换，所以尝试使用你的脚本生成字体，但是一直报错，请问是什么原因呢
python版本是 `3.10.12`

![屏幕截图 2023-10-17 141632](https://github.com/chenh96/yahei-sarasa/assets/146551891/f1659a50-34bc-46e4-a62b-c4f599ffd81a)

**Comment by chenh96** [comment]
download 函数会传入一个 url，你应该是修改了 `url = get_latest()` 那一段代码。
get.py 只是用来下载并解压最新字体压缩包的，想要换个字体生成的话，应该修改 gen.py 中的 gen_regular、gen_bold、gen_light 三个函数中的读取字体文件名。
修改几个 .py 文件开头的本地缓存目录，然后执行 `python3 auto.py`，会自动下载并处理最新的字体。

**Comment by ffainy** [comment]
`get_latest()` 这个函数我只改了这一句 `name = 'sarasa-gothic-unhinted-ttf-' + version + '.7z'`，因为我想用unhinted的版本，难道是这个改动导致的报错，我不懂python所以不知道是不是这个原因。

**Comment by ffainy** [comment]
啊我知道了，应该是 `gothic-ttf-unhinted`，我手残了 🤣

**Comment by ffainy** [comment]
感谢耐心回复，问题已解决
