### ISSUE TITLE
为什么数字部分的间距很大

### ISSUE THREAD

**Issue by Edmondguo** [chenh96/yahei-sarasa#6]
你好，我发现直接从release下载的数字部分比从更纱黑体的github下载的SarasaGothicSC-Regular.ttf的数字部分要宽，这是为什么呢？
![image](https://github.com/user-attachments/assets/e3c86624-e5c5-4353-ac07-3c6f6557b413)

**Comment by chenh96** [comment]
本项目 Release 中的字体默认来自于 Sarasa Ui SC，我自己对比了一下，Ui 中的数字确实比 Gothic 中的宽一些。
突然感觉基于 Gothic 也挺好的，我自己先编一个版本，后面再看要不要默认基于 Gothic 构建。

**Comment by chenh96** [comment]
经过测试，Ui 相比 Gothic 之所以数字总长度更宽，是因为它的数字是等宽的，这在很多需要对齐显示的场合看起来要更舒服一些。

**Comment by Edmondguo** [comment]
> 经过测试，Ui 相比 Gothic 之所以数字总长度更宽，是因为它的数字是等宽的，这在很多需要对齐显示的场合看起来要更舒服一些。

在中文数字混排场景是对齐比较舒服，不过有个比较尴尬的问题是输一连串数字的时候比如手机号码的时候，违和感非常重
![image](https://github.com/user-attachments/assets/8bd52f1d-3991-4b20-8fc8-22f219d25d6a)

**Comment by chenh96** [comment]
> > 经过测试，Ui 相比 Gothic 之所以数字总长度更宽，是因为它的数字是等宽的，这在很多需要对齐显示的场合看起来要更舒服一些。
> 
> 在中文数字混排场景是对齐比较舒服，不过有个比较尴尬的问题是输一连串数字的时候比如手机号码的时候，违和感非常重 ![image](https://private-user-images.githubusercontent.com/43534972/373886620-8bd52f1d-3991-4b20-8fc8-22f219d25d6a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgxODc5MDAsIm5iZiI6MTcyODE4NzYwMCwicGF0aCI6Ii80MzUzNDk3Mi8zNzM4ODY2MjAtOGJkNTJmMWQtMzk5MS00YjIwLThmYzgtMjJmMjE5ZDI1ZDZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA2VDA0MDY0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZhYjMyZTI1ZDcyODQ1NTBmYjEzYmI3NjFkM2M1ZjQ1NDk2Yzc4ZDcwNmIyNWFkZDkzMmI5MTg3MTc3ZjVlZGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.gmhnhTuYfcKUgKHMRhGxXiGL8B4b8hJI_cdPZLtQ2yU)

应该暂时不会提供默认的 Gothic 版本，但是我会在后续制作过程中考虑这个问题，如果急着要的话，可以先自己尝试搭建一个 Ubuntu 虚拟环境，按照教程构建一份。

**Comment by Edmondguo** [comment]
> > > 经过测试，Ui 相比 Gothic 之所以数字总长度更宽，是因为它的数字是等宽的，这在很多需要对齐显示的场合看起来要更舒服一些。
> > 
> > 
> > 在中文数字混排场景是对齐比较舒服，不过有个比较尴尬的问题是输一连串数字的时候比如手机号码的时候，违和感非常重 ![image](https://private-user-images.githubusercontent.com/43534972/373886620-8bd52f1d-3991-4b20-8fc8-22f219d25d6a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgxODc5MDAsIm5iZiI6MTcyODE4NzYwMCwicGF0aCI6Ii80MzUzNDk3Mi8zNzM4ODY2MjAtOGJkNTJmMWQtMzk5MS00YjIwLThmYzgtMjJmMjE5ZDI1ZDZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA2VDA0MDY0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZhYjMyZTI1ZDcyODQ1NTBmYjEzYmI3NjFkM2M1ZjQ1NDk2Yzc4ZDcwNmIyNWFkZDkzMmI5MTg3MTc3ZjVlZGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.gmhnhTuYfcKUgKHMRhGxXiGL8B4b8hJI_cdPZLtQ2yU)
> 
> 应该暂时不会提供默认的 Gothic 版本，但是我会在后续制作过程中考虑这个问题，如果急着要的话，可以先自己尝试搭建一个 Ubuntu 虚拟环境，按照教程构建一份。

我在Ubuntu尝试了，不过遇到了一些问题，apt安装了fontForge和python3-fontForge后，python导入FontForge还是提示找不到包，一直没解决。我看FontForge官网的安装方式也没有用包管理器安装
